name: ChatCore
version: '${project.version}'
main: me.cranked.chatcore.ChatCore
api-version: 1.13
authors: [ Cranked ]
description: Everything you'll ever need in a chat plugin
website: https://www.mc-market.org/resources/13998/
softdepend: [PlaceholderAPI, Vault]
commands:
  chat:
    description: bring up chat commands
    aliases: [c, chatcore]
